services:
  web:
    image: web-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file: .env
    environment:
      - LLMX_CONFIG_PATH=/config/cfg.yml
    volumes:
      - ./config:/config