# Sets the the default model to use for llm() when no provider parameter is set.
model:
  provider: google
  parameters:
    api_key: null
    model: models/gemini-2.5-flash-lite-preview-09-2025
    thinking_budget: 0
providers:
  google:
    name: google
    description: Google's Gemini models
    models:
      - name: Gemini 2.5 Flash Lite
        max_tokens: 16384
        model:
          provider: gemini
          parameters:
            model: models/gemini-2.5-flash-lite-preview-09-2025
            thinking_budget: 0
      - name: Gemini 2.5 Flash
        max_tokens: 16384
        model:
          provider: gemini
          parameters:
            model: models/gemini-2.5-flash
            thinking_budget: 0

