# Sets the the default model to use for llm() when no provider parameter is set.
model:
  provider: anthropic
  parameters:
    api_key: null

providers:
  anthropic:
    name: anthropic
    description: Anthropic's Claude models
    models:
      - name: claude-3-5-sonnet-20241022
        max_tokens: 8192
        model:
          provider: anthropic
          parameters:
            model: claude-3-5-sonnet-20241022
